#############################################################################
# Makefile for building: ChartCreator/ChartCreator
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  OOPPROJECT.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile OOPPROJECT.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -IChartCreator/build/moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ChartCreator1.0.0
DISTDIR = /home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE\ AD\ OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/obj/ChartCreator1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Charts.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ChartCreator/build/obj/

####### Files

SOURCES       = cppFiles/area.cpp \
		cppFiles/arealinepiesettings.cpp \
		cppFiles/bar.cpp \
		cppFiles/barsettings.cpp \
		cppFiles/candlestick.cpp \
		cppFiles/candlesticksettings.cpp \
		cppFiles/chart.cpp \
		cppFiles/chartselection.cpp \
		cppFiles/chartsettings.cpp \
		cppFiles/controller.cpp \
		cppFiles/line.cpp \
		cppFiles/main.cpp \
		cppFiles/mainwindow.cpp \
		cppFiles/pie.cpp ChartCreator/build/rcc/qrc_application.cpp \
		ChartCreator/build/moc/moc_area.cpp \
		ChartCreator/build/moc/moc_arealinepiesettings.cpp \
		ChartCreator/build/moc/moc_bar.cpp \
		ChartCreator/build/moc/moc_barsettings.cpp \
		ChartCreator/build/moc/moc_candlestick.cpp \
		ChartCreator/build/moc/moc_candlesticksettings.cpp \
		ChartCreator/build/moc/moc_chart.cpp \
		ChartCreator/build/moc/moc_chartselection.cpp \
		ChartCreator/build/moc/moc_chartsettings.cpp \
		ChartCreator/build/moc/moc_controller.cpp \
		ChartCreator/build/moc/moc_line.cpp \
		ChartCreator/build/moc/moc_mainwindow.cpp \
		ChartCreator/build/moc/moc_pie.cpp
OBJECTS       = ChartCreator/build/obj/area.o \
		ChartCreator/build/obj/arealinepiesettings.o \
		ChartCreator/build/obj/bar.o \
		ChartCreator/build/obj/barsettings.o \
		ChartCreator/build/obj/candlestick.o \
		ChartCreator/build/obj/candlesticksettings.o \
		ChartCreator/build/obj/chart.o \
		ChartCreator/build/obj/chartselection.o \
		ChartCreator/build/obj/chartsettings.o \
		ChartCreator/build/obj/controller.o \
		ChartCreator/build/obj/line.o \
		ChartCreator/build/obj/main.o \
		ChartCreator/build/obj/mainwindow.o \
		ChartCreator/build/obj/pie.o \
		ChartCreator/build/obj/qrc_application.o \
		ChartCreator/build/obj/moc_area.o \
		ChartCreator/build/obj/moc_arealinepiesettings.o \
		ChartCreator/build/obj/moc_bar.o \
		ChartCreator/build/obj/moc_barsettings.o \
		ChartCreator/build/obj/moc_candlestick.o \
		ChartCreator/build/obj/moc_candlesticksettings.o \
		ChartCreator/build/obj/moc_chart.o \
		ChartCreator/build/obj/moc_chartselection.o \
		ChartCreator/build/obj/moc_chartsettings.o \
		ChartCreator/build/obj/moc_controller.o \
		ChartCreator/build/obj/moc_line.o \
		ChartCreator/build/obj/moc_mainwindow.o \
		ChartCreator/build/obj/moc_pie.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		OOPPROJECT.pro hFiles/area.h \
		hFiles/arealinepiesettings.h \
		hFiles/bar.h \
		hFiles/barsettings.h \
		hFiles/candlestick.h \
		hFiles/candlesticksettings.h \
		hFiles/chart.h \
		hFiles/chartselection.h \
		hFiles/chartsettings.h \
		hFiles/controller.h \
		hFiles/flags.h \
		hFiles/line.h \
		hFiles/mainwindow.h \
		hFiles/pie.h cppFiles/area.cpp \
		cppFiles/arealinepiesettings.cpp \
		cppFiles/bar.cpp \
		cppFiles/barsettings.cpp \
		cppFiles/candlestick.cpp \
		cppFiles/candlesticksettings.cpp \
		cppFiles/chart.cpp \
		cppFiles/chartselection.cpp \
		cppFiles/chartsettings.cpp \
		cppFiles/controller.cpp \
		cppFiles/line.cpp \
		cppFiles/main.cpp \
		cppFiles/mainwindow.cpp \
		cppFiles/pie.cpp
QMAKE_TARGET  = ChartCreator
DESTDIR       = ChartCreator/
TARGET        = ChartCreator/ChartCreator


first: all
####### Build rules

ChartCreator/ChartCreator:  $(OBJECTS)  
	@test -d ChartCreator/ || mkdir -p ChartCreator/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OOPPROJECT.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		OOPPROJECT.pro \
		application.qrc
	$(QMAKE) -o Makefile OOPPROJECT.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
OOPPROJECT.pro:
application.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile OOPPROJECT.pro

qmake_all: FORCE


all: Makefile ChartCreator/ChartCreator

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents application.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents hFiles/area.h hFiles/arealinepiesettings.h hFiles/bar.h hFiles/barsettings.h hFiles/candlestick.h hFiles/candlesticksettings.h hFiles/chart.h hFiles/chartselection.h hFiles/chartsettings.h hFiles/controller.h hFiles/flags.h hFiles/line.h hFiles/mainwindow.h hFiles/pie.h $(DISTDIR)/
	$(COPY_FILE) --parents cppFiles/area.cpp cppFiles/arealinepiesettings.cpp cppFiles/bar.cpp cppFiles/barsettings.cpp cppFiles/candlestick.cpp cppFiles/candlesticksettings.cpp cppFiles/chart.cpp cppFiles/chartselection.cpp cppFiles/chartsettings.cpp cppFiles/controller.cpp cppFiles/line.cpp cppFiles/main.cpp cppFiles/mainwindow.cpp cppFiles/pie.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: ChartCreator/build/rcc/qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) ChartCreator/build/rcc/qrc_application.cpp
ChartCreator/build/rcc/qrc_application.cpp: application.qrc \
		/usr/lib/qt5/bin/rcc \
		files/Guida.html \
		icons/BarChart.png \
		icons/CandlestickChart.png \
		icons/CenterAlign.png \
		icons/Reset.png \
		icons/SliceExplode.png \
		icons/ColumnParse.png \
		icons/LineChart.png \
		icons/PdfExport.png \
		icons/AreaChart.png \
		icons/RowSelect.png \
		icons/RightAlign.png \
		icons/Save.png \
		icons/PieChart.png \
		icons/TextSettings.png \
		icons/StackedAreaChart.png \
		icons/Back.png \
		icons/HistogramChart.png \
		icons/NewGraph.png \
		icons/NewColumn.png \
		icons/RowParse.png \
		icons/LeftAlign.png \
		icons/Erase.png \
		icons/ColorSettings.png \
		icons/Delete.png \
		icons/NewRow.png
	/usr/lib/qt5/bin/rcc -name application application.qrc -o ChartCreator/build/rcc/qrc_application.cpp

compiler_moc_predefs_make_all: ChartCreator/build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) ChartCreator/build/moc/moc_predefs.h
ChartCreator/build/moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o ChartCreator/build/moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: ChartCreator/build/moc/moc_area.cpp ChartCreator/build/moc/moc_arealinepiesettings.cpp ChartCreator/build/moc/moc_bar.cpp ChartCreator/build/moc/moc_barsettings.cpp ChartCreator/build/moc/moc_candlestick.cpp ChartCreator/build/moc/moc_candlesticksettings.cpp ChartCreator/build/moc/moc_chart.cpp ChartCreator/build/moc/moc_chartselection.cpp ChartCreator/build/moc/moc_chartsettings.cpp ChartCreator/build/moc/moc_controller.cpp ChartCreator/build/moc/moc_line.cpp ChartCreator/build/moc/moc_mainwindow.cpp ChartCreator/build/moc/moc_pie.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) ChartCreator/build/moc/moc_area.cpp ChartCreator/build/moc/moc_arealinepiesettings.cpp ChartCreator/build/moc/moc_bar.cpp ChartCreator/build/moc/moc_barsettings.cpp ChartCreator/build/moc/moc_candlestick.cpp ChartCreator/build/moc/moc_candlesticksettings.cpp ChartCreator/build/moc/moc_chart.cpp ChartCreator/build/moc/moc_chartselection.cpp ChartCreator/build/moc/moc_chartsettings.cpp ChartCreator/build/moc/moc_controller.cpp ChartCreator/build/moc/moc_line.cpp ChartCreator/build/moc/moc_mainwindow.cpp ChartCreator/build/moc/moc_pie.cpp
ChartCreator/build/moc/moc_area.cpp: hFiles/area.h \
		hFiles/chart.h \
		hFiles/flags.h \
		ChartCreator/build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include hFiles/area.h -o ChartCreator/build/moc/moc_area.cpp

ChartCreator/build/moc/moc_arealinepiesettings.cpp: hFiles/arealinepiesettings.h \
		hFiles/chartsettings.h \
		hFiles/chart.h \
		hFiles/flags.h \
		ChartCreator/build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include hFiles/arealinepiesettings.h -o ChartCreator/build/moc/moc_arealinepiesettings.cpp

ChartCreator/build/moc/moc_bar.cpp: hFiles/bar.h \
		hFiles/chart.h \
		hFiles/flags.h \
		ChartCreator/build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include hFiles/bar.h -o ChartCreator/build/moc/moc_bar.cpp

ChartCreator/build/moc/moc_barsettings.cpp: hFiles/barsettings.h \
		hFiles/arealinepiesettings.h \
		hFiles/chartsettings.h \
		hFiles/chart.h \
		hFiles/flags.h \
		hFiles/bar.h \
		ChartCreator/build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include hFiles/barsettings.h -o ChartCreator/build/moc/moc_barsettings.cpp

ChartCreator/build/moc/moc_candlestick.cpp: hFiles/candlestick.h \
		hFiles/chart.h \
		hFiles/flags.h \
		ChartCreator/build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include hFiles/candlestick.h -o ChartCreator/build/moc/moc_candlestick.cpp

ChartCreator/build/moc/moc_candlesticksettings.cpp: hFiles/candlesticksettings.h \
		hFiles/chartsettings.h \
		hFiles/chart.h \
		hFiles/flags.h \
		ChartCreator/build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include hFiles/candlesticksettings.h -o ChartCreator/build/moc/moc_candlesticksettings.cpp

ChartCreator/build/moc/moc_chart.cpp: hFiles/chart.h \
		hFiles/flags.h \
		ChartCreator/build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include hFiles/chart.h -o ChartCreator/build/moc/moc_chart.cpp

ChartCreator/build/moc/moc_chartselection.cpp: hFiles/chartselection.h \
		ChartCreator/build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include hFiles/chartselection.h -o ChartCreator/build/moc/moc_chartselection.cpp

ChartCreator/build/moc/moc_chartsettings.cpp: hFiles/chartsettings.h \
		hFiles/chart.h \
		hFiles/flags.h \
		ChartCreator/build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include hFiles/chartsettings.h -o ChartCreator/build/moc/moc_chartsettings.cpp

ChartCreator/build/moc/moc_controller.cpp: hFiles/controller.h \
		hFiles/mainwindow.h \
		hFiles/flags.h \
		hFiles/chartselection.h \
		hFiles/chartsettings.h \
		hFiles/chart.h \
		hFiles/arealinepiesettings.h \
		hFiles/candlesticksettings.h \
		hFiles/barsettings.h \
		hFiles/bar.h \
		ChartCreator/build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include hFiles/controller.h -o ChartCreator/build/moc/moc_controller.cpp

ChartCreator/build/moc/moc_line.cpp: hFiles/line.h \
		hFiles/chart.h \
		hFiles/flags.h \
		ChartCreator/build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include hFiles/line.h -o ChartCreator/build/moc/moc_line.cpp

ChartCreator/build/moc/moc_mainwindow.cpp: hFiles/mainwindow.h \
		hFiles/flags.h \
		hFiles/chartselection.h \
		hFiles/chartsettings.h \
		hFiles/chart.h \
		hFiles/arealinepiesettings.h \
		hFiles/candlesticksettings.h \
		hFiles/barsettings.h \
		hFiles/bar.h \
		ChartCreator/build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include hFiles/mainwindow.h -o ChartCreator/build/moc/moc_mainwindow.cpp

ChartCreator/build/moc/moc_pie.cpp: hFiles/pie.h \
		hFiles/chart.h \
		hFiles/flags.h \
		ChartCreator/build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT/ChartCreator/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I'/home/dipo/Documents/Università/INFORMATICA/PROGRAMMAZIONE AD OGGETTI/ProgettoPao_21-22/OOPPROJECT' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include hFiles/pie.h -o ChartCreator/build/moc/moc_pie.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

ChartCreator/build/obj/area.o: cppFiles/area.cpp hFiles/area.h \
		hFiles/chart.h \
		hFiles/flags.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/area.o cppFiles/area.cpp

ChartCreator/build/obj/arealinepiesettings.o: cppFiles/arealinepiesettings.cpp hFiles/arealinepiesettings.h \
		hFiles/chartsettings.h \
		hFiles/chart.h \
		hFiles/flags.h \
		hFiles/area.h \
		hFiles/line.h \
		hFiles/pie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/arealinepiesettings.o cppFiles/arealinepiesettings.cpp

ChartCreator/build/obj/bar.o: cppFiles/bar.cpp hFiles/bar.h \
		hFiles/chart.h \
		hFiles/flags.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/bar.o cppFiles/bar.cpp

ChartCreator/build/obj/barsettings.o: cppFiles/barsettings.cpp hFiles/barsettings.h \
		hFiles/arealinepiesettings.h \
		hFiles/chartsettings.h \
		hFiles/chart.h \
		hFiles/flags.h \
		hFiles/bar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/barsettings.o cppFiles/barsettings.cpp

ChartCreator/build/obj/candlestick.o: cppFiles/candlestick.cpp hFiles/candlestick.h \
		hFiles/chart.h \
		hFiles/flags.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/candlestick.o cppFiles/candlestick.cpp

ChartCreator/build/obj/candlesticksettings.o: cppFiles/candlesticksettings.cpp hFiles/candlesticksettings.h \
		hFiles/chartsettings.h \
		hFiles/chart.h \
		hFiles/flags.h \
		hFiles/candlestick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/candlesticksettings.o cppFiles/candlesticksettings.cpp

ChartCreator/build/obj/chart.o: cppFiles/chart.cpp hFiles/chart.h \
		hFiles/flags.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/chart.o cppFiles/chart.cpp

ChartCreator/build/obj/chartselection.o: cppFiles/chartselection.cpp hFiles/chartselection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/chartselection.o cppFiles/chartselection.cpp

ChartCreator/build/obj/chartsettings.o: cppFiles/chartsettings.cpp hFiles/chartsettings.h \
		hFiles/chart.h \
		hFiles/flags.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/chartsettings.o cppFiles/chartsettings.cpp

ChartCreator/build/obj/controller.o: cppFiles/controller.cpp hFiles/controller.h \
		hFiles/mainwindow.h \
		hFiles/flags.h \
		hFiles/chartselection.h \
		hFiles/chartsettings.h \
		hFiles/chart.h \
		hFiles/arealinepiesettings.h \
		hFiles/candlesticksettings.h \
		hFiles/barsettings.h \
		hFiles/bar.h \
		hFiles/candlestick.h \
		hFiles/area.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/controller.o cppFiles/controller.cpp

ChartCreator/build/obj/line.o: cppFiles/line.cpp hFiles/line.h \
		hFiles/chart.h \
		hFiles/flags.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/line.o cppFiles/line.cpp

ChartCreator/build/obj/main.o: cppFiles/main.cpp hFiles/controller.h \
		hFiles/mainwindow.h \
		hFiles/flags.h \
		hFiles/chartselection.h \
		hFiles/chartsettings.h \
		hFiles/chart.h \
		hFiles/arealinepiesettings.h \
		hFiles/candlesticksettings.h \
		hFiles/barsettings.h \
		hFiles/bar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/main.o cppFiles/main.cpp

ChartCreator/build/obj/mainwindow.o: cppFiles/mainwindow.cpp hFiles/mainwindow.h \
		hFiles/flags.h \
		hFiles/chartselection.h \
		hFiles/chartsettings.h \
		hFiles/chart.h \
		hFiles/arealinepiesettings.h \
		hFiles/candlesticksettings.h \
		hFiles/barsettings.h \
		hFiles/bar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/mainwindow.o cppFiles/mainwindow.cpp

ChartCreator/build/obj/pie.o: cppFiles/pie.cpp hFiles/pie.h \
		hFiles/chart.h \
		hFiles/flags.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/pie.o cppFiles/pie.cpp

ChartCreator/build/obj/qrc_application.o: ChartCreator/build/rcc/qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/qrc_application.o ChartCreator/build/rcc/qrc_application.cpp

ChartCreator/build/obj/moc_area.o: ChartCreator/build/moc/moc_area.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/moc_area.o ChartCreator/build/moc/moc_area.cpp

ChartCreator/build/obj/moc_arealinepiesettings.o: ChartCreator/build/moc/moc_arealinepiesettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/moc_arealinepiesettings.o ChartCreator/build/moc/moc_arealinepiesettings.cpp

ChartCreator/build/obj/moc_bar.o: ChartCreator/build/moc/moc_bar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/moc_bar.o ChartCreator/build/moc/moc_bar.cpp

ChartCreator/build/obj/moc_barsettings.o: ChartCreator/build/moc/moc_barsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/moc_barsettings.o ChartCreator/build/moc/moc_barsettings.cpp

ChartCreator/build/obj/moc_candlestick.o: ChartCreator/build/moc/moc_candlestick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/moc_candlestick.o ChartCreator/build/moc/moc_candlestick.cpp

ChartCreator/build/obj/moc_candlesticksettings.o: ChartCreator/build/moc/moc_candlesticksettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/moc_candlesticksettings.o ChartCreator/build/moc/moc_candlesticksettings.cpp

ChartCreator/build/obj/moc_chart.o: ChartCreator/build/moc/moc_chart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/moc_chart.o ChartCreator/build/moc/moc_chart.cpp

ChartCreator/build/obj/moc_chartselection.o: ChartCreator/build/moc/moc_chartselection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/moc_chartselection.o ChartCreator/build/moc/moc_chartselection.cpp

ChartCreator/build/obj/moc_chartsettings.o: ChartCreator/build/moc/moc_chartsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/moc_chartsettings.o ChartCreator/build/moc/moc_chartsettings.cpp

ChartCreator/build/obj/moc_controller.o: ChartCreator/build/moc/moc_controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/moc_controller.o ChartCreator/build/moc/moc_controller.cpp

ChartCreator/build/obj/moc_line.o: ChartCreator/build/moc/moc_line.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/moc_line.o ChartCreator/build/moc/moc_line.cpp

ChartCreator/build/obj/moc_mainwindow.o: ChartCreator/build/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/moc_mainwindow.o ChartCreator/build/moc/moc_mainwindow.cpp

ChartCreator/build/obj/moc_pie.o: ChartCreator/build/moc/moc_pie.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChartCreator/build/obj/moc_pie.o ChartCreator/build/moc/moc_pie.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

